# A push on master will build, test and publish Jeka on OSSRH.
# Beside it will push the built documentation on the Jeka landing page.

# If a tag is present on the last commit, Jeka will publish versioned artifacts according tag name on OSSRH public repo.
# If no tag is present, the built artifacts will be published to OSSRH snapshot repository.
# This logic is implemented within the Jeka build.

name: Java Build and Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Jekaw
      env:
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        OSSRH_PWD: ${{ secrets.OSSRH_PWD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        cd ./dev.jeka.plugins.protobuf
        ./jekaw java#pack java#publish
